# Generated by Django 5.2.14 on 2026-07-01 17:00

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-is_featured", "name"],
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("out_of_stock", "Out of Stock"),
                    ("coming_soon", "Coming Soon"),
                ],
                db_index=True,
                default="available",
                max_length=20,
                verbose_name="وضعیت موجودی",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.product_image_path,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, verbose_name="مواد اولیه"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="ویژه"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="نام محصول"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=220, verbose_name="نامک"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
    ]
