# Generated by Django 5.2.14 on 2026-06-01 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryzone",
            name="express_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="code",
            field=models.SlugField(
                choices=[
                    ("tehran", "Tehran"),
                    ("tehran_suburbs", "Tehran Suburbs"),
                    ("other_cities", "Other Cities"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="free_delivery_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Subtotal above which standard courier delivery is free.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
