# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fulfillment",
            "0002_deliveryzone_express_fee_alter_deliveryzone_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryzone",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "منطقه ارسال",
                "verbose_name_plural": "مناطق ارسال",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "لاگ وضعیت سفارش",
                "verbose_name_plural": "لاگ\u200cهای وضعیت سفارش",
            },
        ),
    ]
