# Generated by Django 5.2.14 on 2026-06-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_fee_order_delivery_zone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("courier", "Courier"),
                    ("express", "Express"),
                    ("pickup", "Pickup"),
                    ("cod", "COD Delivery"),
                ],
                db_index=True,
                default="courier",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("cod_pending", "COD Pending"),
                    ("cod_confirmed", "COD Confirmed"),
                    ("cash_received", "Cash Received"),
                    ("failed", "Failed"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_processed", "Refund Processed"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("confirmed_by_shop", "Confirmed by Shop"),
                    ("preparing", "Preparing"),
                    ("packaged", "Packaged"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=30,
            ),
        ),
    ]
