# Generated by Django 5.2.14 on 2026-06-07 12:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fulfillment",
            "0002_deliveryzone_express_fee_alter_deliveryzone_code_and_more",
        ),
        ("orders", "0005_counter_payment_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Legacy delivery fee",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("pickup", "In-cafe pickup"),
                    ("courier", "Courier (legacy)"),
                    ("express", "Express (legacy)"),
                    ("cod", "COD (legacy)"),
                ],
                db_index=True,
                default="pickup",
                help_text="Active in-cafe orders use pickup. Legacy courier/COD values are retained for history.",
                max_length=20,
                verbose_name="Fulfillment type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fulfillment.deliveryzone",
                verbose_name="Delivery zone (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
