# Generated by Django 5.2.14 on 2026-06-07 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fulfillment",
            "0002_deliveryzone_express_fee_alter_deliveryzone_code_and_more",
        ),
        ("growth", "0002_revenue_engine"),
        ("orders", "0006_deprecate_delivery_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="daily_sequence",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="daily_sequence_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["daily_sequence_date", "daily_sequence"],
                name="orders_orde_daily_s_3670d6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("daily_sequence__isnull", False)),
                fields=("daily_sequence_date", "daily_sequence"),
                name="orders_unique_daily_sequence_per_date",
            ),
        ),
    ]
