# Generated by Django 5.2.14 on 2026-07-01 17:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0003_persian_verbose_names"),
        ("orders", "0007_daily_order_sequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "قلم سفارش",
                "verbose_name_plural": "اقلام سفارش",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاریخ ثبت"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="daily_sequence",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="شماره روزانه"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="daily_sequence_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="تاریخ شماره روزانه"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="هزینه ارسال (قدیمی)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("pickup", "In-cafe pickup"),
                    ("courier", "Courier (legacy)"),
                    ("express", "Express (legacy)"),
                    ("cod", "COD (legacy)"),
                ],
                db_index=True,
                default="pickup",
                help_text="Active in-cafe orders use pickup. Legacy courier/COD values are retained for history.",
                max_length=20,
                verbose_name="نوع دریافت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="fulfillment.deliveryzone",
                verbose_name="منطقه ارسال (قدیمی)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="order",
            name="fulfillment_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="تاریخ تحویل"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="شماره سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("online", "Online Payment"),
                    ("cash", "Cash at Counter"),
                    ("counter_card", "Card at Counter"),
                ],
                db_index=True,
                default="online",
                max_length=20,
                verbose_name="روش پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("cod_pending", "COD Pending"),
                    ("cod_confirmed", "COD Confirmed"),
                    ("cash_received", "Cash Received"),
                    ("failed", "Failed"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_processed", "Refund Processed"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=30,
                verbose_name="وضعیت پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promotion_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="تخفیف پروموشن",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("paid", "Paid"),
                    ("confirmed_by_shop", "Confirmed by Shop"),
                    ("preparing", "Preparing"),
                    ("packaged", "Packaged"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=30,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="جمع جزء"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="مبلغ نهایی"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="fulfillment_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تحویل"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="جمع خط"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=200, verbose_name="نام محصول"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="قیمت واحد"
            ),
        ),
    ]
