# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-updated_at"],
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "پروفایل مشتری",
                "verbose_name_plural": "پروفایل\u200cهای مشتری",
            },
        ),
    ]
