# Generated by Django 5.2.14 on 2026-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_coupon_code",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="cart",
            name="referral_code",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
