# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_active_checkout_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "سبد خرید", "verbose_name_plural": "سبدهای خرید"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["created_at"],
                "verbose_name": "قلم سبد",
                "verbose_name_plural": "اقلام سبد",
            },
        ),
    ]
