# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loyaltyaccount",
            options={
                "ordering": ["-lifetime_points"],
                "verbose_name": "حساب وفاداری",
                "verbose_name_plural": "حساب\u200cهای وفاداری",
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltytransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تراکنش وفاداری",
                "verbose_name_plural": "تراکنش\u200cهای وفاداری",
            },
        ),
    ]
