# Generated by Django 5.2.14 on 2026-06-07 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_background_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="تلفن")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="سن"
                    ),
                ),
                (
                    "desired_position",
                    models.CharField(
                        choices=[
                            ("barista", "باریستا"),
                            ("cashier", "صندوقدار"),
                            ("waiter", "گارسون"),
                            ("chef", "سرآشپز"),
                            ("assistant_chef", "کمک سرآشپز"),
                            ("pastry_chef", "شیرینی\u200cپز"),
                            ("service_cleaning", "خدمات / نظافت"),
                            ("other", "سایر"),
                        ],
                        max_length=32,
                        verbose_name="سمت مورد نظر",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("none", "بدون سابقه"),
                            ("under_1_year", "کمتر از ۱ سال"),
                            ("1_to_3_years", "۱ تا ۳ سال"),
                            ("over_3_years", "بیش از ۳ سال"),
                        ],
                        max_length=32,
                        verbose_name="سابقه کار",
                    ),
                ),
                (
                    "residence_area",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="محل سکونت"
                    ),
                ),
                (
                    "morning_shift",
                    models.CharField(
                        choices=[
                            ("yes", "بله"),
                            ("no", "خیر"),
                            ("some_days", "برخی روزها"),
                        ],
                        max_length=16,
                        verbose_name="شیفت صبح",
                    ),
                ),
                (
                    "evening_shift",
                    models.CharField(
                        choices=[
                            ("yes", "بله"),
                            ("no", "خیر"),
                            ("some_days", "برخی روزها"),
                        ],
                        max_length=16,
                        verbose_name="شیفت عصر",
                    ),
                ),
                (
                    "weekend_availability",
                    models.CharField(
                        choices=[("yes", "بله"), ("no", "خیر")],
                        max_length=8,
                        verbose_name="آمادگی آخر هفته",
                    ),
                ),
                (
                    "expected_salary",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="حقوق درخواستی"
                    ),
                ),
                ("motivation", models.TextField(verbose_name="انگیزه همکاری")),
                ("strengths", models.TextField(verbose_name="نقاط قوت")),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        upload_to="careers/resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="رزومه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("reviewing", "در حال بررسی"),
                            ("interview", "مصاحبه"),
                            ("rejected", "رد شده"),
                            ("hired", "استخدام شده"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="یادداشت مدیر"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "درخواست همکاری",
                "verbose_name_plural": "درخواست\u200cهای همکاری",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="backgroundtasklog",
            new_name="core_backgr_task_na_d28412_idx",
            old_name="core_backgr_task_na_6f8b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="backgroundtasklog",
            new_name="core_backgr_created_2e57b0_idx",
            old_name="core_backgr_created_0a1c4d_idx",
        ),
    ]
