# Generated by Django 5.2.14 on 2026-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_career_application"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CareerApplication",
        ),
    ]
