# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_careerapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backgroundtasklog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "لاگ وظیفه پس\u200cزمینه",
                "verbose_name_plural": "لاگ\u200cهای وظایف پس\u200cزمینه",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyanalyticssnapshot",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "تصویر تحلیل روزانه",
                "verbose_name_plural": "تصاویر تحلیل روزانه",
            },
        ),
    ]
