# Generated by Django 5.2.14 on 2026-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="irr", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("cod", "Cash on Delivery")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("cod", "Cash on Delivery")],
                max_length=20,
            ),
        ),
    ]
