# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_counter_payment_providers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "رویداد پرداخت",
                "verbose_name_plural": "رویدادهای پرداخت",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="مبلغ"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="irr", max_length=3, verbose_name="ارز"),
        ),
    ]
