# Generated by Django 5.2.14 on 2026-06-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_delivery_fee_order_delivery_zone_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_stock", models.BooleanField(default=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                (
                    "allow_preorder",
                    models.BooleanField(
                        default=True,
                        help_text="Allow booking beyond today's capacity on future production days.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product inventories",
            },
        ),
        migrations.CreateModel(
            name="DailyProductionCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_date", models.DateField(db_index=True)),
                ("max_units", models.PositiveIntegerField()),
                ("reserved_units", models.PositiveIntegerField(default=0)),
                ("fulfilled_units", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_capacities",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["production_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "production_date"],
                        name="inventory_d_product_f39400_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "production_date"),
                        name="unique_daily_capacity_per_product",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("production_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("confirmed", "Confirmed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "production_date"],
                        name="inventory_s_status_5e8ea4_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="inventory_s_order_i_9b314c_idx",
                    ),
                ],
            },
        ),
    ]
