# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockreservation_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyproductioncapacity",
            options={
                "ordering": ["production_date"],
                "verbose_name": "ظرفیت تولید روزانه",
                "verbose_name_plural": "ظرفیت\u200cهای تولید روزانه",
            },
        ),
        migrations.AlterModelOptions(
            name="productinventory",
            options={
                "verbose_name": "موجودی محصول",
                "verbose_name_plural": "موجودی محصولات",
            },
        ),
        migrations.AlterModelOptions(
            name="stockreservation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "رزرو موجودی",
                "verbose_name_plural": "رزروهای موجودی",
            },
        ),
    ]
