# Generated by Django 5.2.14 on 2026-06-01 13:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_revenue_engine"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerIntelligenceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("behavioral_tags", models.JSONField(blank=True, default=list)),
                ("engagement_score", models.PositiveIntegerField(default=0)),
                ("category_affinity", models.JSONField(blank=True, default=dict)),
                (
                    "discount_sensitivity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("preferred_product_ids", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntelligenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-report_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report_date", "period"),
                        name="unique_intelligence_snapshot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductIntelligenceMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "margin_boost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Ranking multiplier for high-margin boosting (1.0 = neutral).",
                        max_digits=5,
                    ),
                ),
                ("is_cookie", models.BooleanField(default=False)),
                ("is_coffee", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_meta",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UpsellImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("product", "Product Detail"),
                            ("cart", "Cart"),
                            ("checkout", "Checkout"),
                            ("sms", "SMS Personalization"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("product_ids", models.JSONField(default=list)),
                ("converted", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "conversion_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductBakeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_date", models.DateField(db_index=True)),
                ("suggested_bake_qty", models.PositiveIntegerField(default=0)),
                (
                    "forecast_demand",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("capacity_available", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("low_stock", "Low Stock Warning"),
                            ("overstock_risk", "Overstock Risk"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bake_recommendations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-recommendation_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "recommendation_date"),
                        name="unique_bake_recommendation_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductCoPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co_count", models.PositiveIntegerField(default=0)),
                (
                    "affinity_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_purchase_from",
                        to="products.product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_purchase_to",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "-affinity_score"],
                        name="intelligenc_product_6d419a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "related_product"),
                        name="unique_co_purchase_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_date", models.DateField(db_index=True)),
                ("units_sold", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("peak_hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("hourly_distribution", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-stat_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "stat_date"),
                        name="unique_product_daily_stat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductDemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_for_date", models.DateField(db_index=True)),
                ("window_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "predicted_units",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "historical_avg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "weekday_factor",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_for_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "forecast_for_date", "window_days"),
                        name="unique_product_forecast",
                    )
                ],
            },
        ),
    ]
