# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerintelligenceprofile",
            options={
                "verbose_name": "پروفایل هوش مشتری",
                "verbose_name_plural": "پروفایل\u200cهای هوش مشتری",
            },
        ),
        migrations.AlterModelOptions(
            name="intelligencesnapshot",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "تصویر هوش تجاری",
                "verbose_name_plural": "تصاویر هوش تجاری",
            },
        ),
        migrations.AlterModelOptions(
            name="productbakerecommendation",
            options={
                "ordering": ["-recommendation_date"],
                "verbose_name": "توصیه پخت",
                "verbose_name_plural": "توصیه\u200cهای پخت",
            },
        ),
        migrations.AlterModelOptions(
            name="productcopurchase",
            options={
                "verbose_name": "خرید همزمان",
                "verbose_name_plural": "خریدهای همزمان",
            },
        ),
        migrations.AlterModelOptions(
            name="productdailystats",
            options={
                "ordering": ["-stat_date"],
                "verbose_name": "آمار روزانه محصول",
                "verbose_name_plural": "آمار روزانه محصولات",
            },
        ),
        migrations.AlterModelOptions(
            name="productdemandforecast",
            options={
                "ordering": ["-forecast_for_date"],
                "verbose_name": "پیش\u200cبینی تقاضا",
                "verbose_name_plural": "پیش\u200cبینی\u200cهای تقاضا",
            },
        ),
        migrations.AlterModelOptions(
            name="productintelligencemeta",
            options={
                "verbose_name": "متای هوش محصول",
                "verbose_name_plural": "متاهای هوش محصول",
            },
        ),
        migrations.AlterModelOptions(
            name="upsellimpression",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "نمایش پیشنهاد فروش",
                "verbose_name_plural": "نمایش\u200cهای پیشنهاد فروش",
            },
        ),
    ]
