from django.db import models


class BackgroundTaskLog(models.Model):
    """Lightweight observability for async jobs (success, retry, dead-letter)."""

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        STARTED = "started", "Started"
        SUCCESS = "success", "Success"
        FAILURE = "failure", "Failure"
        RETRY = "retry", "Retry"
        DEAD = "dead", "Dead Letter"

    task_name = models.CharField(max_length=255, db_index=True)
    task_id = models.CharField(max_length=255, unique=True)
    idempotency_key = models.CharField(max_length=255, blank=True, db_index=True)
    queue = models.CharField(max_length=64, blank=True)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.PENDING)
    payload = models.JSONField(default=dict, blank=True)
    result = models.JSONField(null=True, blank=True)
    error_message = models.TextField(blank=True)
    retry_count = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "لاگ وظیفه پس‌زمینه"
        verbose_name_plural = "لاگ‌های وظایف پس‌زمینه"
        indexes = [
            models.Index(fields=["task_name", "status"]),
            models.Index(fields=["created_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.task_name} [{self.status}]"


class DailyAnalyticsSnapshot(models.Model):
    """Persisted daily sales report generated by Celery Beat."""

    report_date = models.DateField(unique=True)
    payload = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-report_date"]
        verbose_name = "تصویر تحلیل روزانه"
        verbose_name_plural = "تصاویر تحلیل روزانه"

    def __str__(self) -> str:
        return f"Analytics {self.report_date}"
