# Generated by Django 5.2.14 on 2026-06-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerapplication",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="careerapplication",
            name="linkedin_url",
        ),
    ]
