# Generated by Django 5.2.14 on 2026-06-12 16:17

import careers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0005_cafe_hiring_form_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "درخواست همکاری",
                "verbose_name_plural": "درخواست\u200cهای همکاری",
            },
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="desired_position",
            field=models.CharField(
                choices=[
                    ("barista", "باریستا"),
                    ("cashier", "صندوق\u200cدار"),
                    ("waiter", "سالن کار"),
                    ("kitchen_staff", "نیروی آشپزخانه"),
                    ("baker", "بیکر"),
                    ("pastry_assistant", "کمک بیکر"),
                    ("shift_supervisor", "سرپرست شیفت"),
                    ("cleaner", "خدمات و نظافت"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="موقعیت شغلی",
            ),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="full_name",
            field=models.CharField(max_length=120, verbose_name="نام و نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="hr_answers",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="پاسخ\u200cهای HR"
            ),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="شماره تماس"),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="resume_file",
            field=models.FileField(
                blank=True,
                upload_to=careers.models.career_resume_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="رزومه",
            ),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سابقه کار (سال)",
            ),
        ),
    ]
