# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0002_revenue_engine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abandonedcarttracker",
            options={
                "ordering": ["-last_activity_at"],
                "verbose_name": "سبد رها شده",
                "verbose_name_plural": "سبدهای رها شده",
            },
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "کوپن",
                "verbose_name_plural": "کوپن\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="couponredemption",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "استفاده از کوپن",
                "verbose_name_plural": "استفاده\u200cهای کوپن",
            },
        ),
        migrations.AlterModelOptions(
            name="customerclvprofile",
            options={
                "verbose_name": "پروفایل ارزش مشتری",
                "verbose_name_plural": "پروفایل\u200cهای ارزش مشتری",
            },
        ),
        migrations.AlterModelOptions(
            name="customersegment",
            options={
                "ordering": ["code"],
                "verbose_name": "بخش مشتری",
                "verbose_name_plural": "بخش\u200cهای مشتری",
            },
        ),
        migrations.AlterModelOptions(
            name="customersegmentmembership",
            options={
                "verbose_name": "عضویت بخش مشتری",
                "verbose_name_plural": "عضویت\u200cهای بخش مشتری",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyrevenuesnapshot",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "تصویر درآمد روزانه",
                "verbose_name_plural": "تصاویر درآمد روزانه",
            },
        ),
        migrations.AlterModelOptions(
            name="funnelanalyticssnapshot",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "تصویر قیف فروش",
                "verbose_name_plural": "تصاویر قیف فروش",
            },
        ),
        migrations.AlterModelOptions(
            name="growthevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "رویداد رشد",
                "verbose_name_plural": "رویدادهای رشد",
            },
        ),
        migrations.AlterModelOptions(
            name="promotioncampaign",
            options={
                "verbose_name": "کمپین پروموشن",
                "verbose_name_plural": "کمپین\u200cهای پروموشن",
            },
        ),
        migrations.AlterModelOptions(
            name="promotionrule",
            options={
                "ordering": ["priority", "-created_at"],
                "verbose_name": "قانون پروموشن",
                "verbose_name_plural": "قوانین پروموشن",
            },
        ),
        migrations.AlterModelOptions(
            name="referral",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "معرفی",
                "verbose_name_plural": "معرفی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="referralcode",
            options={"verbose_name": "کد معرف", "verbose_name_plural": "کدهای معرف"},
        ),
        migrations.AlterModelOptions(
            name="revenueattribution",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "انتساب درآمد",
                "verbose_name_plural": "انتساب\u200cهای درآمد",
            },
        ),
    ]
