# Generated by Django 5.2.14 on 2026-07-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smslog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "لاگ پیامک",
                "verbose_name_plural": "لاگ\u200cهای پیامک",
            },
        ),
        migrations.AlterModelOptions(
            name="smstemplate",
            options={
                "ordering": ["category", "code"],
                "verbose_name": "قالب پیامک",
                "verbose_name_plural": "قالب\u200cهای پیامک",
            },
        ),
    ]
